language: java
sudo: true
dist: trusty
jdk: oraclejdk11
addons:
  sonarcloud:
    organization: "dionrats-github"
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
services:
  - 'docker'
install:
  - mvn install
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      ./mvnw install dockerfile:build ;
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push drats/documents ;
    fi