language: java
sudo: true
dist: trusty
jdk: oraclejdk11
addons:
  sonarcloud:
    organization: "dionrats-github"
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
install:
- mvn install
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar